// SPDX-FileCopyrightText: 2025 Anna-Lena Marx <mail@marx.engineer>
//
// SPDX-License-Identifier: MPL-2.0

// CONTEXT(NAME)
CONTEXT(INIT)
CONTEXT(MENU_BOOKS)
CONTEXT(MENU_CHAPTERS)
CONTEXT(READING)
CONTEXT(SETTINGS)
