# SPDX-FileCopyrightText: 2025 Florian Limberger <flo@purplekraken.com>
#
# SPDX-License-Identifier: MPL-2.0

# Native_sim uses simulated flash instead of an SD card
CONFIG_FLASH=y

# This needs the FUSE development headers installed:
#CONFIG_FUSE_FS_ACCESS=y
