# SPDX-FileCopyrightText: 2025 Anna-Lena Marx <mail@marx.engineer>
#
# SPDX-License-Identifier: MPL-2.0

name: Build Zephyr ZEReader Application

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4

  build:
    name: "Build Zephyr ZEReader App"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi
          manifest-file-name: ../west.yml

      - name: Build Firmware
        run: |
          west build -b rpi_pico2/rp2350a/m33 app -p always

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZEReader-Firmware
          path: build/zephyr/zephyr.uf2
 
