name: Build Zephyr ZEReader Application

on: workflow_dispatch

jobs:
  build:
    name: "Build Zephyr ZEReader App"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zephyr
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: app
          toolchains: arm-zephyr-eabi

      - name: Build Firmware
        run: |
          west build -b rpi_pico2/rp2350a/m33 app -p always

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZEReader-Firmware
          path: build/zephyr/zephyr.uf2
 
